***Assignment - String Based assignment problem***

****Answer -1****

In [2]:
''' Declairing a variable and assigned a value as string'''
r = "harsh"

In [4]:
''' Using slicing method for reverse string'''
r[-1::-1]

'hsrah'

****Answer - 2****

In [16]:
''' Declairing a variable and assigned a value as string'''
p = "abba"

In [19]:
''' i did forward and reverse slicing for given string and
    then compare both sliced output and the result is true it means given string is palindrome'''

p[0::] == p[-1::-1]

True

****Answer-3****

In [23]:
''' Declairing a variable and assigned a value as string'''
u = "harsh"

In [26]:
'''converting in upper case using upper function'''
u.upper()

'HARSH'

****Answer-4****

In [28]:
''' Declairing a variable and assigned a value as string'''
l = "PW SKILLS"

In [30]:
'''converting in lowercase using lower function'''
l.lower()

'pw skills'

****Answer-5****

In [4]:
'''converting in lowercase using lower function'''
c = "pw skills classes are good and sudhanshu sir is teaching well"

In [5]:
'''counting vowels in given string'''

[c.count("a"),c.count("e"),c.count("i"),c.count("o"),c.count("u")]

[5, 4, 4, 2, 2]

****Answer-6****

In [85]:
'''Taken a Variable consonant an assign value 0 and taken a string str and assign value as string'''

consonant = 0

Str = "harshislearningpythonfrompwskillsclasses"


In [86]:
''' Using for loop and if else condition that if vowel available in string then dont add count in consonant if not available then add'''

for i in Str:
    if i =="a" or i =="e" or i =="i" or i =="o" or i =="u":
        consonant  = consonant
    else:
        consonant = consonant+1

In [87]:
'''Total No of constant in string'''
consonant

30

****Answer-7****

In [90]:
'''Taken a variable and assigned a string'''
m = "Hi my name is harsh gupta im learning python and practicing as well"

In [95]:
'''Using replace to remoove all whitespaces from string'''

m.replace(" ","")

'Himynameisharshguptaimlearningpythonandpracticingaswell'

****Answer-8****

In [146]:
S = "harsh"
count = 0

In [147]:
'''used for loop to find length of the string'''

for i in S:
    count = count+1

In [150]:
count

5

****Answer-9****

In [151]:
a = "Almond Solution"

In [165]:
''' for check string contain specific word used for loop
     and i given condition if t is available in string then
     print yes else print NO'''

for i in a:
    if i =="t":
        print("yes")
    else:
        print("No")
         
        

No
No
No
No
No
No
No
No
No
No
No
yes
No
No
No


****Answer-10****

In [166]:
R = "harsh gupta"

In [168]:
'''using Replace function i replace a word h with m'''

R.replace("h","m")

'marsm gupta'

****Answer-11****

In [173]:
C = "PW Skills"

In [175]:
'''Using count fnction and given word l to check occurnace of this word and get output'''

C.count("l")

2

****Answer-12****

In [176]:
F = "PW Skills classes"

In [179]:
''' To find first occurance of string used find function
    which return me index No of first occurance of that word'''

F.find("l")

6

****Answer-13****

In [181]:
x = "PW Skills classes"

In [183]:
''' usied rfind function which help me to find last occurance for word l'''

x.rfind("l")

11

****Answer-14****

In [3]:
s = "Harsh is data science aspirants"

In [4]:
s.split()

['Harsh', 'is', 'data', 'science', 'aspirants']

****Answer-15****

In [7]:
a = ["h","a","r","s","h"]

In [21]:
'''Using join function to concat word in to string''' 

s = ("".join(a))

In [24]:
s

'harsh'

****Answer-16****

In [25]:
''' String where word are seperated by spaces'''
q = "Harsh is student of PWSkills and he is learning python"

In [27]:
q.replace(" ","_")

'Harsh_is_student_of_PWSkills_and_he_is_learning_python'

****Answer-19****

In [21]:
'''taken variable k and assigned an string'''

k = "hello world"

In [22]:
k.title()

'Hello World'

****Answer-20****

In [23]:
a = "Hello everyone good morning this is python class"

In [26]:
l = a.split()

In [30]:
l

['Hello', 'everyone', 'good', 'morning', 'this', 'is', 'python', 'class']

****Answer-22****

In [7]:
a = "my name is harsh"

In [9]:
a[-1::-1]

'hsrah si eman ym'

****Answer-23*

In [10]:
s1 = "fa34snfj4"

In [12]:
s1.isalnum()

True

****Answer-29****

In [2]:
a = "fhgj2344dggg"

In [3]:
a.strip('f')

'hgj2344dggg'

****Answer-31****

In [10]:
a1 = "harsh.hg89@gmail.com"

In [12]:
a1[0:5:]

'harsh'

*****Answer-32****

In [14]:
a2 = "harsh.hg89@gmail.com"

In [33]:
a2[11:]

'gmail.com'

****Answer-35****

In [54]:
a3 = "https://youtube.com/"

In [56]:
a3[0:5]

'https'

****Answer-38****

In [57]:
a4 = "hadnf5663"

In [59]:
a4.isnumeric()

False

****Answer-39****

In [60]:
a5 = "dkfnkfm24343"

In [62]:
a5.isalpha()

False

****Answer-40****

In [19]:
a6 = "Harsh"

In [20]:
list(a6)

['H', 'a', 'r', 's', 'h']

****Answer-41****

In [28]:
a7 = "cat"

In [24]:
a8 = "act"

In [31]:
def check(a7,a8):
    if(sorted(a7)==sorted(a8)):
        print("its ana")
    else:
        print("its not")

****Answer-45****

In [33]:
s1 = "aaabbbccc"

In [44]:
set(s1)

{'a', 'b', 'c'}

In [46]:
len(set(s1))

3

****Answer-47****

In [49]:
s2 = "harsh"

In [51]:
s2.

SyntaxError: invalid syntax (476066579.py, line 1)

In [52]:
a = "Harsh"

In [1]:
del a(1)

SyntaxError: cannot delete function call (3284277842.py, line 1)

***List Based Question***

****Answer-1****

In [2]:
L = [1,2,3,4,5,6,7,8,9,10]

In [4]:
type(L)

list

****Answer-2****

In [18]:
L1 = ["Harsh","Abhi","Raj",1,2,4,5]

In [19]:
count = 0

In [20]:
for i in L1:
    count = count+1

In [22]:
count

7

****Answer-3****

In [23]:
L2 = ["harsh","pw","maths"]

In [32]:
L2.append("Chemistry")

In [34]:
L2

['harsh',
 'pw',
 'maths',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry']

****Answer-4****

In [36]:
L3 = ["Physics","Chemistry","Maths"]

In [40]:
L3.insert(2,"Biology")

In [42]:
L3

['Physics', 'Chemistry', 'Biology', 'Maths']

****Answer-5****

In [60]:
L4 =["Almond","atechnos","Wipro","Google"]

In [63]:
L4.remove("Almond")

In [65]:
L4

['atechnos', 'Wipro', 'Google']

****Answer-6****

In [69]:
L5 = [1,2,3,4,5,9]

In [70]:
L5.pop(1)

2

In [72]:
L5

[1, 3, 4, 5, 9]

****Answer-7****

In [2]:
L6 = ["Harsh",3,4,2,5,6]

In [ ]:
L6.index("Harsh")

0

****Answer-8****

In [6]:
L7 = ["Harsh","Harsh",6,4,5]

In [8]:
L7.index("Harsh")

0

****Answer-9****

In [ ]:
L8 = ["PW","PW",4,5,6]

In [ ]:
L8.count("PW")

2

****Answer-11****

In [37]:
L9 = [9,5,9,3,1,6]

In [39]:
L9.sort()

In [41]:
L9

[1, 3, 5, 6, 9, 9]

****Answer-12****

In [42]:
L10 = [1,2,3,4,5,6,7,8]

In [57]:
L10.sort(reverse=True)

In [59]:
L10

[8, 7, 6, 5, 4, 3, 2, 1]

****Answer-13****

In [90]:
even_number =[]

In [91]:
for i in range(1,11):
    even_number.append(i*2)
    print(even_number)

[2]
[2, 4]
[2, 4, 6]
[2, 4, 6, 8]
[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10, 12]
[2, 4, 6, 8, 10, 12, 14]
[2, 4, 6, 8, 10, 12, 14, 16]
[2, 4, 6, 8, 10, 12, 14, 16, 18]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


****Answer-14****

In [93]:
odd_number = []

In [94]:
for i in range(0,10):
    odd_number.append(i*2+1)
    print(odd_number)

[1]
[1, 3]
[1, 3, 5]
[1, 3, 5, 7]
[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9, 11]
[1, 3, 5, 7, 9, 11, 13]
[1, 3, 5, 7, 9, 11, 13, 15]
[1, 3, 5, 7, 9, 11, 13, 15, 17]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


****Answer-15****

In [96]:
L12 = [3,4,2,5,7,9]

In [99]:
sum(L12)

30

****Answer-16****

In [100]:
L13 = [9,2,4,6,1,5]

In [102]:
max(L13)

9

****Answer-17****

In [103]:
L14 = [91,2,4,1,5,8,3]

In [105]:
min(L14)

1

****Answer-18****

In [134]:
squar_list =[]

In [136]:
for i in range(1,10):
    squar_list.append(i**2)
    print(squar_list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 1]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4, 9, 16]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4, 9, 16, 25]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4, 9, 16, 25, 36, 49]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4, 9, 16, 25, 36, 49, 64]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 4, 9, 16, 25, 36, 49, 64, 81]


****Answer-19****

In [144]:
random_number = []

In [145]:
import random
for i  in range(20):
    random_number.append(random.randint(1,20))
    print(random_number)

[20]
[20, 5]
[20, 5, 8]
[20, 5, 8, 1]
[20, 5, 8, 1, 18]
[20, 5, 8, 1, 18, 12]
[20, 5, 8, 1, 18, 12, 2]
[20, 5, 8, 1, 18, 12, 2, 5]
[20, 5, 8, 1, 18, 12, 2, 5, 8]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10, 19]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10, 19, 7]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10, 19, 7, 3]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10, 19, 7, 3, 17]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10, 19, 7, 3, 17, 19]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10, 19, 7, 3, 17, 19, 16]
[20, 5, 8, 1, 18, 12, 2, 5, 8, 5, 7, 5, 10, 19, 7, 3, 17, 19, 16, 10]


****Answer-20****

In [153]:
L20 = [1,2,3,4,1,3,4,2,5,6,5]

set(L20)

In [155]:
list(set(L20))

[1, 2, 3, 4, 5, 6]

In [169]:
m = [1,2,3,4,5]
n = [5,6,7,8,9]


def common_value(m,n):
    m_set = set(m)
    n_set = set(n)
    if(m_set & n_set):
        print(m_set & n_set)
    else:
        print("no common value")        

In [172]:
m,n

([1, 2, 3, 4, 5], [5, 6, 7, 8, 9])

In [174]:
common_value(m,n)

{5}


****Answer-22****

In [3]:
L1 = [1,2,3,4,5,6,7,8]
L2 = [5,7,8,9]
L3 = []

In [4]:
for i in L1:
    if L1 not in L2:
        L3.append(i)

In [6]:
L3

[1, 2, 3, 4, 5, 6, 7, 8]

****Answer-23****

In [9]:
L1 = [1,2,3,4,5]
L2 = [8,7,9,5,4]

In [11]:
L1+L2

[1, 2, 3, 4, 5, 8, 7, 9, 5, 4]

****Answer-24****

In [14]:
from operator import*
L1 = [5,4,3,2,9]
p = 2
for i in L1:
    p = mul(i,p)
    print(p)
    

10
40
120
240
2160


****Answer-25****

In [22]:
L1 = [2,3,4,6,8,9]
L2 = []

In [23]:
for i in L1:
    if i%2==0:
        L2.append(i)
        

In [25]:
print(L2)

[2, 4, 6, 8]


****Answer-26****

In [40]:
L8 = ['1','2','3','4','5','6']

In [41]:
for i in range(0,len(L8)):
    L8[i]=int(L8[i])

In [48]:
L8

[1, 2, 3, 4, 5, 6]

****Answer-27****

In [44]:
L9 = [1,2,3,4,5,6]

In [46]:
for i in range(0,len(L9)):
    L9[i]=str(L9[i])

In [50]:
L9

['1', '2', '3', '4', '5', '6']

****Answer-28****

In [51]:
L7 = [[1,2],[3,4],[5,6]]

In [53]:
flat_list = sum(L7,[])

In [55]:
flat_list

[1, 2, 3, 4, 5, 6]

****Answer-30****

In [64]:
L6 = [5,6,3,2,4,1]
flag = 0

In [66]:
if(L6 == sorted(L6)):
    flag = 1
    
if(flag):
    print("yes sorted")
else:
    print("not sorted")

not sorted


****Answer-33****

In [11]:
for i in range(2,51):
    for j in range(2,51):
        if i%j==0:
            break
    if i ==j:
        print(i,end=",")

2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,

****Answer-34****

In [5]:
def chunks(lst,n):
    for i in range(0,len(lst),n):
        yield lst[i:i+1]

    

In [7]:
import pprint
pprint.pprint(list(chunks(range(10,75),10)))

[range(10, 11),
 range(20, 21),
 range(30, 31),
 range(40, 41),
 range(50, 51),
 range(60, 61),
 range(70, 71)]


In [9]:
import numpy as np
lst = range(50)
np.array_split(lst,5)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]

****Answer - 35****

In [12]:
L1 = [8,4,5,9,2,3]

In [14]:
L2 = list(set(L1))

In [16]:
L2.sort()

In [18]:
print("2nd largest no is",L2[-2])

2nd largest no is 8


****Answer-36****

In [24]:
L = [2,3,4,5,6]

In [25]:
L1 = []

In [26]:
for i in L:
    L1.append(i**2)
    print(L1)

[4]
[4, 9]
[4, 9, 16]
[4, 9, 16, 25]
[4, 9, 16, 25, 36]


****Answer-37****

In [1]:
ListName = ["harsh","rahul","dinesh","pankaj"]

In [2]:
name_dict = {}

In [6]:
for i ,name in enumerate(ListName):
    name_dict[i] = name
    print(name_dict)

{1: 'pankaj', 0: 'harsh'}
{1: 'rahul', 0: 'harsh'}
{1: 'rahul', 0: 'harsh', 2: 'dinesh'}
{1: 'rahul', 0: 'harsh', 2: 'dinesh', 3: 'pankaj'}


****Answer-38****

In [7]:
L = [9,3,6,7,2,8,1,4,5]

In [10]:
import random
random.shuffle(L)

In [12]:
print("Suffle list is  "+str(L))

Suffle list is  [7, 5, 3, 6, 4, 8, 2, 9, 1]


****Answer-39****

In [2]:
L= {1,2,3,4,5,6,7,8,9,10}
fact = 1
for i in L:
    for number in range(1,i+1):
        fact = fact*number
    print("factorial of"  ,i, "is",  fact)

factorial of 1 is 1
factorial of 2 is 2
factorial of 3 is 12
factorial of 4 is 288
factorial of 5 is 34560
factorial of 6 is 24883200
factorial of 7 is 125411328000
factorial of 8 is 5056584744960000
factorial of 9 is 1834933472251084800000
factorial of 10 is 6658606584104736522240000000


****Answer No - 40****

In [26]:
L1 = [1,2,3,4,5,6]
L2 = [9,7,11,10,6]


In [28]:
def common_data(L1,L2):
    result = false
    for i in L1:
        for j in L2:
            if i==j:
                result = True
                return result
                
            

****Answer - 41*****

In [34]:
L = [1,2,3,4,5]

In [35]:
L.clear()

In [37]:
L

[]

****Answer-43****

In [40]:
S= "PWSklls"

In [42]:
list(S)

['P', 'W', 'S', 'k', 'l', 'l', 's']

****Answer - 44****

In [2]:
L = ['H','a','r','s','h']

In [3]:
string = " ".join(L)

In [4]:
string

'H a r s h'

****Answer-45****

In [37]:
def squar(n):
    power = n
    mylist = []
    for i in range(1,n+1):
        mylist.append(2**i)
    return mylist

In [40]:
squar(10)

[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]

****Answer-46****

In [86]:
mylist = ["harshgupta","pwskills","sudhanshu","krishNaik"]

maxlist = max(mylist,key= len)

print(maxlist)
    

harshgupta


*****Answer-47****

In [87]:
mylist = ["harshgupta","pwskills","sudhanshu","krishNaik"]

minlist = min(mylist,key= len)

print(minlist)

pwskills


****Answer-48****

In [114]:
def triangular_series(n):
    j = 1
    k =1
    
    for i in range(n):
        print(k,end=' ')
        j = j+1
        k = j+k
        

In [117]:
triangular_series(10)

1 3 6 10 15 21 28 36 45 55 

****Answer - 49****

In [3]:
L1 = ['harsh','krish','sudhanshu','pwskills']
L2 = ['harsh','krish','sudhanshu','pwskills']

result = all(elem in L1 for elem in L2)

if result:
    print('yes element ont there')
    
else:
    print('no not available')


yes element ont there


****Answer-50****

In [ ]:
L = [0,12,3,4,5]