In [3]:
import numpy as np

Answer-1

In [5]:
arr1 = np.array([1,3,5,7,9])

In [7]:
arr2 = np.array([2,4,5,8])

In [8]:
arr1

array([1, 3, 5, 7, 9])

In [10]:
arr2

array([2, 4, 5, 8])

In [12]:
np.intersect1d(arr1,arr2)

array([5])

Answer-2

In [14]:
arr1 = np.array([12,3,1,7,8,20])

In [15]:
arr1

array([12,  3,  1,  7,  8, 20])

Answer-2

In [20]:
def  K_smallest(arr,n,k):
    for i in range(0,n):
        for j in range (0,n-i-1):
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j],arr[j+1]
    return arr[k-1]
arr = np.array([12,3,1,7,8,20])
n=len(arr)
k=3
print(K_smallest(arr,n,k))





1


Answer-3

In [2]:
def binary_search(arr,low,High,x):
    if High>=low:
        mid = (High+low)//2
        if arr[mid]==x:
            return mid
        elif arr[mid]>x:
            return binary_search(arr,low,mid-1,x)
        else:
            return binary_search(arr,mid+1,High,x)
    else:
        return-1
arr = [4,5,6,7,8,9,1,2,3]
x = 6
result = binary_search(arr,0,len(arr)-1,x)
if result!=-1:
    print("is",str(result))
else:
    print("NO")

is 2


Answer-4

In [7]:
def liner_search(arr,target):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if(arr[i][j]==target):
                return [i,j]
    return [-1,-1]
arr = [[1,3,5],[7,9,11],[13,15,17]]
target = 11
ans = liner_search(arr,target)
print(ans)

[1, 2]


Answer-5

In [14]:
def sorting(ist):
    ist2 = sorted(ist,key = len)
    return ist2
ist = ['apple', 'banana', 'kiwi', 'orange', 'grape']
print(sorting(ist))

['kiwi', 'apple', 'grape', 'banana', 'orange']


Answer-9

In [18]:
def findpeak(arr,n):
    if(n==1):
        return 0 
    if (arr[0]>=arr[1]):
        return 0
    if (arr[n-1]>=arr[n-2]):
        return n-1
    for i in range(1,n-1):
        if(arr[i]>=arr[i-1] and arr[i] >= arr[i+1]):
            return i
arr = [1,3,20,4,1,0]
n= len(arr)
print(findpeak(arr,n))








2


Answer-10

In [8]:
def insertionsort(A,size):
    i , kay,j = 0,0,0
    for i in range(size):
        key = A[i]
        j   =i-1
        while j>=0 and A[j]>key:
            
            A[j+1]=A[j]
            j=j-1
        A[j+1]=key
        
        
        