In [2]:
import numpy as np

Answer- 1

Answer-2

Answer-3

In [16]:
l = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]]

In [18]:
arr = np.array(l)

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr.size

12

In [21]:
arr.shape

(3, 4)

In [22]:
arr.ndim

2

Answer-4

In [23]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
arr[0,]

array([1, 2, 3, 4])

In [27]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[2:3]

array([[ 9, 10, 11, 12]])

In [37]:
arr[0:3,(3,)]

array([[ 4],
       [ 8],
       [12]])

Answer-6

In [38]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr[0:3,(0,1,3)]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

Answer-7

In [50]:
np.random.randint(0,2,(3,3))

array([[0, 1, 1],
       [1, 1, 0],
       [0, 1, 1]])

Answer-10

randn generates numbers from a normal distribution with a mean of 0 and a standard deviation of 1, while `rand` generates numbers from a uniform distribution between 0 and 1

Answer-11

In [61]:
A = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
B = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

1

In [59]:
np.multiply(A,B)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [64]:
A

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [66]:
B

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [70]:
arr1 = np.array(A)

In [71]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
arr2 = np.array(B)

In [74]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
arr1*arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [77]:
2

2

In [79]:
np.matrix(arr1+arr2)

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [82]:
np.matrix(arr2-arr1)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [84]:
np.matrix(arr2/arr1)

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Answer- 12

In [86]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
arr.byteswap(True)

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

Answer-13

Answer-14

np.reshape() function use change the shape of array from row to column

In [92]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
arr1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [100]:
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [102]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Answer - 15